### ISSUE TITLE
v1.0.0 milestone

### ISSUE THREAD

**Issue by Bartozzz** [qilin-editor/qilin-app#42]
## Core
- [ ] Create a plugin system
- [ ] Create a theme manager
- [ ] Separate non-core components into independent repositories

## Design
- [ ] Include icon in releases
- [ ] Make different styles depending on platform

## Functionality
- [ ] Export files as `.pdf`, `.html`

## Ideas
- [ ] Create a custom extension for Qilin projects

**Comment by Bartozzz** [comment]
Plugin manager: https://github.com/qilin-editor/qilin-manager

<blockquote><img src="https://avatars1.githubusercontent.com/u/31961354?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/qilin-editor/qilin-manager">qilin-editor/qilin-manager</a></strong></div><div>qilin-manager - Package manager which automates and manages themes and plugins for Qilin</div></blockquote>

**Comment by Bartozzz** [comment]
Theme related components: https://github.com/qilin-editor/qilin-components

<blockquote><img src="https://avatars1.githubusercontent.com/u/31961354?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/qilin-editor/qilin-components">qilin-editor/qilin-components</a></strong></div><div>qilin-components - A bunch of common components used by Qilin editor and Qilin plugins</div></blockquote>
